package me.shadaj.slinky.generator

object SVGToJSMapping {
  val convert = Map[String, Attr](
    "accent-height" -> Attr("accentHeight", "Double"),
    "accumulate" -> Attr("accumulate"),
    "additive" -> Attr("additive"),
    "alphabetic" -> Attr("alphabetic", "js.Any"),
    "amplitude" -> Attr("amplitude", "js.Any"),
    "arabic-form" -> Attr("arabicForm", "js.Any"),
    "ascent" -> Attr("ascent", "Double"),
    "attributeName" -> Attr("attributeName"),
    "attributeType" -> Attr("attributeType"),
    "azimuth" -> Attr("azimuth", "Double"),
    "baseFrequency" -> Attr("baseFrequency"),
    "baseProfile" -> Attr("baseProfile", "js.Any"),
    "bbox" -> Attr("bbox", "js.Any"),
    "begin" -> Attr("begin"),
    "bias" -> Attr("bias", "Double"),
    "by" -> Attr("by", "js.Any"),
    "calcMode" -> Attr("calcMode"),
    "cap-height" -> Attr("capHeight", "js.Any"),
    "clipPathUnits" -> Attr("clipPathUnits"),
    "contentScriptType" -> Attr("contentScriptType"),
    "contentStyleType" -> Attr("contentStyleType"),
    "cx" -> Attr("cx", "Double"),
    "cy" -> Attr("cy", "Double"),
    "d" -> Attr("d", "js.Any"),
    "descent" -> Attr("descent", "js.Any"),
    "diffuseConstant" -> Attr("diffuseConstant", "js.Any"),
    "divisor" -> Attr("divisor", "js.Any"),
    "dur" -> Attr("dur", "js.Any"),
    "dx" -> Attr("dx", "js.Any"),
    "dy" -> Attr("dy", "js.Any"),
    "edgeMode" -> Attr("edgeMode", "js.Any"),
    "elevation" -> Attr("elevation", "js.Any"),
    "end" -> Attr("end", "js.Any"),
    "exponent" -> Attr("exponent", "js.Any"),
    "externalResourcesRequired" -> Attr("externalResourcesRequired", "js.Any"),
    "fill" -> Attr("fill", "js.Any"),
    "filterRes" -> Attr("filterRes", "js.Any"),
    "filterUnits" -> Attr("filterUnits", "js.Any"),
    "font-family" -> Attr("fontFamily", "js.Any"),
    "font-size" -> Attr("fontSize", "js.Any"),
    "font-stretch" -> Attr("fontStretch", "js.Any"),
    "font-style" -> Attr("fontStyle", "js.Any"),
    "format" -> Attr("format", "js.Any"),
    "from" -> Attr("from", "js.Any"),
    "fx" -> Attr("fx", "Double"),
    "fy" -> Attr("fy", "Double"),
    "g1" -> Attr("g1", "js.Any"),
    "g2" -> Attr("g2", "js.Any"),
    "glyph-name" -> Attr("glyphName", "js.Any"),
    "glyphRef" -> Attr("glyphRef", "js.Any"),
    "gradientTransform" -> Attr("gradientTransform", "js.Any"),
    "gradientUnits" -> Attr("gradientUnits", "js.Any"),
    "hanging" -> Attr("hanging", "js.Any"),
    "horiz-adv-x" -> Attr("horizAdvX", "js.Any"),
    "horiz-origin-x" -> Attr("horizOriginX", "js.Any"),
    "horiz-origin-y" -> Attr("horizOriginY", "js.Any"),
    "ideographic" -> Attr("ideographic", "js.Any"),
    "in" -> Attr("in", "js.Any"),
    "in2" -> Attr("in2", "js.Any"),
    "intercept" -> Attr("intercept", "js.Any"),
    "k" -> Attr("k", "js.Any"),
    "k1" -> Attr("k1", "js.Any"),
    "k2" -> Attr("k2", "js.Any"),
    "k3" -> Attr("k3", "js.Any"),
    "k4" -> Attr("k4", "js.Any"),
    "kernelMatrix" -> Attr("kernelMatrix", "js.Any"),
    "kernelUnitLength" -> Attr("kernelUnitLength", "js.Any"),
    "keyPoints" -> Attr("keyPoints", "js.Any"),
    "keySplines" -> Attr("keySplines", "js.Any"),
    "keyTimes" -> Attr("keyTimes", "js.Any"),
    "lengthAdjust" -> Attr("lengthAdjust", "js.Any"),
    "limitingConeAngle" -> Attr("limitingConeAngle", "js.Any"),
    "local" -> Attr("local", "js.Any"),
    "markerHeight" -> Attr("markerHeight", "js.Any"),
    "markerUnits" -> Attr("markerUnits", "js.Any"),
    "markerWidth" -> Attr("markerWidth", "js.Any"),
    "maskContentUnits" -> Attr("maskContentUnits", "js.Any"),
    "maskUnits" -> Attr("maskUnits", "js.Any"),
    "mathematical" -> Attr("mathematical", "js.Any"),
    "mode" -> Attr("mode", "js.Any"),
    "numOctaves" -> Attr("numOctaves", "js.Any"),
    "offset" -> Attr("offset", "js.Any"),
    "operator" -> Attr("operator", "js.Any"),
    "order" -> Attr("order", "js.Any"),
    "orient" -> Attr("orient", "js.Any"),
    "orientation" -> Attr("orientation", "js.Any"),
    "origin" -> Attr("origin", "js.Any"),
    "overline-position" -> Attr("overlinePosition", "js.Any"),
    "overline-thickness" -> Attr("overlineThickness", "js.Any"),
    "panose-1" -> Attr("panose1", "js.Any"),
    "path" -> Attr("path", "js.Any"),
    "pathLength" -> Attr("pathLength", "js.Any"),
    "patternContentUnits" -> Attr("patternContentUnits", "js.Any"),
    "patternTransform" -> Attr("patternTransform", "js.Any"),
    "patternUnits" -> Attr("patternUnits", "js.Any"),
    "points" -> Attr("points", "js.Any"),
    "pointsAtX" -> Attr("pointsAtX", "js.Any"),
    "pointsAtY" -> Attr("pointsAtY", "js.Any"),
    "pointsAtZ" -> Attr("pointsAtZ", "js.Any"),
    "preserveAlpha" -> Attr("preserveAlpha", "js.Any"),
    "preserveAspectRatio" -> Attr("preserveAspectRatio", "js.Any"),
    "primitiveUnits" -> Attr("primitiveUnits", "js.Any"),
    "r" -> Attr("r", "js.Any"),
    "radius" -> Attr("radius", "js.Any"),
    "refX" -> Attr("refX", "js.Any"),
    "refY" -> Attr("refY", "js.Any"),
    "rendering-intent" -> Attr("renderingIntent", "js.Any"),
    "repeatCount" -> Attr("repeatCount", "js.Any"),
    "repeatDur" -> Attr("repeatDur", "js.Any"),
    "requiredExtensions" -> Attr("requiredExtensions", "js.Any"),
    "requiredFeatures" -> Attr("requiredFeatures", "js.Any"),
    "restart" -> Attr("restart", "js.Any"),
    "result" -> Attr("result", "js.Any"),
    "rotate" -> Attr("rotate", "js.Any"),
    "rx" -> Attr("rx", "js.Any"),
    "ry" -> Attr("ry", "js.Any"),
    "scale" -> Attr("scale", "js.Any"),
    "seed" -> Attr("seed", "js.Any"),
    "slope" -> Attr("slope", "js.Any"),
    "spacing" -> Attr("spacing", "js.Any"),
    "specularConstant" -> Attr("specularConstant", "js.Any"),
    "specularExponent" -> Attr("specularExponent", "js.Any"),
    "spreadMethod" -> Attr("spreadMethod", "js.Any"),
    "startOffset" -> Attr("startOffset", "js.Any"),
    "stdDeviation" -> Attr("stdDeviation", "js.Any"),
    "stemh" -> Attr("stemh", "js.Any"),
    "stemv" -> Attr("stemv", "js.Any"),
    "stitchTiles" -> Attr("stitchTiles", "js.Any"),
    "strikethrough-position" -> Attr("strikethroughPosition", "js.Any"),
    "strikethrough-thickness" -> Attr("strikethroughThickness", "js.Any"),
    "string" -> Attr("string", "js.Any"),
    "surfaceScale" -> Attr("surfaceScale", "js.Any"),
    "systemLanguage" -> Attr("systemLanguage", "js.Any"),
    "tableValues" -> Attr("tableValues", "js.Any"),
    "targetX" -> Attr("targetX", "js.Any"),
    "targetY" -> Attr("targetY", "js.Any"),
    "textLength" -> Attr("textLength", "js.Any"),
    "to" -> Attr("to", "js.Any"),
    "transform" -> Attr("transform", "js.Any"),
    "u1" -> Attr("u1", "js.Any"),
    "u2" -> Attr("u2", "js.Any"),
    "underline-position" -> Attr("underlinePosition", "js.Any"),
    "underline-thickness" -> Attr("underlineThickness", "js.Any"),
    "unicode" -> Attr("unicode", "js.Any"),
    "unicode-range" -> Attr("unicodeRange", "js.Any"),
    "units-per-em" -> Attr("unitsPerEm", "js.Any"),
    "v-alphabetic" -> Attr("vAlphabetic", "js.Any"),
    "v-hanging" -> Attr("vHanging", "js.Any"),
    "v-ideographic" -> Attr("vIdeographic", "js.Any"),
    "v-mathematical" -> Attr("vMathematical", "js.Any"),
    "values" -> Attr("values", "js.Any"),
    "version" -> Attr("version", "js.Any"),
    "vert-adv-y" -> Attr("vertAdvY", "js.Any"),
    "vert-origin-x" -> Attr("vertOriginX", "js.Any"),
    "vert-origin-y" -> Attr("vertOriginY", "js.Any"),
    "viewBox" -> Attr("viewBox", "js.Any"),
    "viewTarget" -> Attr("viewTarget", "js.Any"),
    "widths" -> Attr("widths", "js.Any"),
    "x" -> Attr("x", "js.Any"),
    "x-height" -> Attr("xHeight", "js.Any"),
    "x1" -> Attr("x1", "js.Any"),
    "x2" -> Attr("x2", "js.Any"),
    "xChannelSelector" -> Attr("xChannelSelector", "js.Any"),
    "xlink" -> Attr("xlink", "js.Any"),
    "xml" -> Attr("xml", "js.Any"),
    "y" -> Attr("y", "js.Any"),
    "y1" -> Attr("y1", "js.Any"),
    "y2" -> Attr("y2", "js.Any"),
    "yChannelSelector" -> Attr("yChannelSelector", "js.Any"),
    "z" -> Attr("z", "js.Any"),
    "zoomAndPan" -> Attr("zoomAndPan", "js.Any"),
    "alignment-baseline" -> Attr("alignmentBaseline"),
    "baseline-shift" -> Attr("baselineShift"),
    "clip-path" -> Attr("clipPath"),
    "clip-rule" -> Attr("clipRule"),
    "clip" -> Attr("clip"),
    "color-interpolation-filters" -> Attr("colorInterpolationFilters"),
    "color-interpolation" -> Attr("colorInterpolation"),
    "color-profile" -> Attr("colorProfile"),
    "color-rendering" -> Attr("colorRendering"),
    "cursor" -> Attr("cursor"),
    "direction" -> Attr("direction", "js.Any"),
    "display" -> Attr("display", "js.Any"),
    "dominant-baseline" -> Attr("dominantBaseline", "js.Any"),
    "enable-background" -> Attr("enableBackground", "js.Any"),
    "fill-opacity" -> Attr("fillOpacity", "js.Any"),
    "fill-rule" -> Attr("fillRule", "js.Any"),
    "filter" -> Attr("filter", "js.Any"),
    "flood-color" -> Attr("floodColor", "js.Any"),
    "flood-opacity" -> Attr("floodOpacity", "js.Any"),
    "font-size-adjust" -> Attr("fontSizeAdjust", "js.Any"),
    "font-variant" -> Attr("fontVariant", "js.Any"),
    "font-weight" -> Attr("fontWeight", "js.Any"),
    "glyph-orientation-horizontal" -> Attr("glyphOrientationHorizontal", "js.Any"),
    "glyph-orientation-vertical" -> Attr("glyphOrientationVertical", "js.Any"),
    "image-rendering" -> Attr("imageRendering", "js.Any"),
    "kerning" -> Attr("kerning", "js.Any"),
    "letter-spacing" -> Attr("letterSpacing", "js.Any"),
    "lighting-color" -> Attr("lightingColor", "js.Any"),
    "marker-end" -> Attr("markerEnd", "js.Any"),
    "marker-mid" -> Attr("markerMid", "js.Any"),
    "marker-start" -> Attr("markerStart", "js.Any"),
    "mask" -> Attr("mask", "js.Any"),
    "opacity" -> Attr("opacity", "js.Any"),
    "overflow" -> Attr("overflow", "js.Any"),
    "pointer-events" -> Attr("pointerEvents", "js.Any"),
    "shape-rendering" -> Attr("shapeRendering", "js.Any"),
    "stop-color" -> Attr("stopColor", "js.Any"),
    "stop-opacity" -> Attr("stopOpacity", "js.Any"),
    "stroke-dasharray" -> Attr("strokeDasharray", "js.Any"),
    "stroke-dashoffset" -> Attr("strokeDashoffset", "js.Any"),
    "stroke-linecap" -> Attr("strokeLinecap", "js.Any"),
    "stroke-linejoin" -> Attr("strokeLinejoin", "js.Any"),
    "stroke-miterlimit" -> Attr("strokeMiterlimit", "js.Any"),
    "stroke-opacity" -> Attr("strokeOpacity", "js.Any"),
    "stroke-width" -> Attr("strokeWidth", "js.Any"),
    "stroke" -> Attr("stroke", "js.Any"),
    "text-anchor" -> Attr("textAnchor", "js.Any"),
    "text-decoration" -> Attr("textDecoration", "js.Any"),
    "text-rendering" -> Attr("textRendering", "js.Any"),
    "unicode-bidi" -> Attr("unicodeBidi", "js.Any"),
    "visibility" -> Attr("visibility", "js.Any"),
    "word-spacing" -> Attr("wordSpacing", "js.Any"),
    "writing-mode" -> Attr("writingMode", "js.Any")
  ).withDefault { k =>
    println(s""""$k" -> Attr("${k.replace("-", "_")}", "js.Any"),""")
    Attr(k.replace("-", "_"), "js.Any")
  } ++ HTMLToJSMapping.convert
}
